/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void joinButtonClick(GButton source, GEvent event) { //_CODE_:joinButton:625211:
  transitionState(new JoinState());
} //_CODE_:joinButton:625211:

public void hostButtonClick(GButton source, GEvent event) { //_CODE_:hostButton:728375:
  transitionState(new HostState());
} //_CODE_:hostButton:728375:

public void instructionsButtonClick(GButton source, GEvent event) { //_CODE_:instructionsButton:373816:
  transitionState(new InstructionsState());
} //_CODE_:instructionsButton:373816:

public void nameTextField_change(GTextField source, GEvent event) { //_CODE_:nameTextField:264905:
  println("nameTextField - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:nameTextField:264905:

public void joinGameButton_click(GButton source, GEvent event) { //_CODE_:joinGameButton:427819:
  println("joinGameButton - GButton >> GEvent." + event + " @ " + millis());
  ClientMessenger m = new ClientMessenger();
  m.init();
  m.writeMessage("joe");
  m.writeMessage("host");
  delay(200);
  println("read: " + m.readMessages());
} //_CODE_:joinGameButton:427819:

public void idTextfield_change(GTextField source, GEvent event) { //_CODE_:idTextField:408355:
  println("idTextField - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:idTextField:408355:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  joinButton = new GButton(this, 311, 129, 166, 62);
  joinButton.setText("JOIN");
  joinButton.addEventHandler(this, "joinButtonClick");
  hostButton = new GButton(this, 313, 207, 165, 57);
  hostButton.setText("HOST");
  hostButton.addEventHandler(this, "hostButtonClick");
  instructionsButton = new GButton(this, 315, 280, 163, 62);
  instructionsButton.setText("INSTRUCTIONS");
  instructionsButton.addEventHandler(this, "instructionsButtonClick");
  nameTextField = new GTextField(this, 297, 354, 200, 30, G4P.SCROLLBARS_NONE);
  nameTextField.setPromptText("Name");
  nameTextField.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  nameTextField.setOpaque(true);
  nameTextField.addEventHandler(this, "nameTextField_change");
  joinGameButton = new GButton(this, 315, 465, 163, 32);
  joinGameButton.setText("Join");
  joinGameButton.addEventHandler(this, "joinGameButton_click");
  idTextField = new GTextField(this, 297, 403, 200, 30, G4P.SCROLLBARS_NONE);
  idTextField.setPromptText("Game ID - Ask the host!");
  idTextField.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  idTextField.setOpaque(true);
  idTextField.addEventHandler(this, "idTextfield_change");
}

// Variable declarations 
// autogenerated do not edit
GButton joinButton; 
GButton hostButton; 
GButton instructionsButton; 
GTextField nameTextField; 
GButton joinGameButton; 
GTextField idTextField; 
