/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button5_click1(GButton source, GEvent event) { //_CODE_:button5:625211:
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button5:625211:

public void button6_click1(GButton source, GEvent event) { //_CODE_:button6:728375:
  println("button6 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button6:728375:

public void button7_click1(GButton source, GEvent event) { //_CODE_:button7:373816:
  println("button7 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button7:373816:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button5 = new GButton(this, 311, 129, 166, 62);
  button5.setText("JOIN");
  button5.addEventHandler(this, "button5_click1");
  button6 = new GButton(this, 313, 207, 165, 57);
  button6.setText("LOBBY");
  button6.addEventHandler(this, "button6_click1");
  button7 = new GButton(this, 315, 281, 163, 62);
  button7.setText("INSTRUCTIONS");
  button7.addEventHandler(this, "button7_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button5; 
GButton button6; 
GButton button7; 
